<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ClassInterpreter.Core\ClassInterpreter.Core.csproj" />
    <ProjectReference Include="..\..\src\ClassInterpreter.Infrastructure\ClassInterpreter.Infrastructure.csproj" />
  </ItemGroup>
</Project>
